
name: CI-numerical

on: [push]
jobs:
  install-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      ‐ name: Setup
        run: npm ci

      ‐ name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
